<span class="title">Branding</span>
<hr class="title-divider">

<div class="right">
    <img width="256" src="images/branding/designs.png">
</div>

Boiled down to its simplest form, the Flashpoint logo is the project's initials flipped against each other. The blank space forms an arrow shape that can be interpreted as a play button or download symbol, a reminder of the processes we've grown accustomed to when accessing our favorite games. The wording typically seen alongside the logo uses the Tahoma font.<br>

Flashpoint's logo falls under the <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0</a> license, meaning it can be freely modified and redistributed so long as Seirade (the logo's designer) or BlueMaxima's Flashpoint receive credit.<br>

A package containing the vectorized logo in various styles may be downloaded <a href="images/branding/logo_sources.7z">here</a>.<br>

<span class="title-small">Wallpapers</span>
<hr>

The following wallpapers are courtesy of Rain:

<div class="wallpaper-container">
    <div class="wallpaper-item">
        <img src="images/branding/wallpapers/fp_generic_thumb.png">
        <b>Generic</b>
        <div class="wallpaper-download">
            <div class="wallpaper-left">SD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_generic_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_generic_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_generic_1600x1200.png">1600x1200</a>
            </div>
            <div class="wallpaper-left">HD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_generic_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_generic_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_generic_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>

    <div class="wallpaper-item">
        <img src="images/branding/wallpapers/fp_shadow_thumb.png">
        <b>Shadow</b>
        <div class="wallpaper-download">
            <div class="wallpaper-left">SD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_shadow_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_shadow_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_shadow_1600x1200.png">1600x1200</a>
            </div>
            <div class="wallpaper-left">HD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_shadow_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_shadow_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_shadow_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>

    <div class="wallpaper-item">
        <img src="images/branding/wallpapers/fp_retro_thumb.png">
        <b>Retrowave</b>
        <div class="wallpaper-download">
            <div class="wallpaper-left">SD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_retro_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_retro_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_retro_1600x1200.png">1600x1200</a>
            </div>
            <div class="wallpaper-left">HD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_retro_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_retro_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_retro_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>
</div>