<span class="title"><?= t('Branding_Title') ?></span>
<hr class="title-divider">

<div class="right">
    <img width="256" src="images/branding/designs.png">
</div>

<?= t('Branding_Para1') ?><br>

<?= t('Branding_Para2', '<a href="https://creativecommons.org/licenses/by/4.0/">') ?><br>

<?= t('Branding_Para3', '<a href="images/branding/logo_sources.7z">') ?><br>

<span class="title-small"><?= t('Wallpapers_Title') ?></span>
<hr>

<?= t('Wallpapers_Desc') ?>

<div class="branding-container">
    <div class="branding-item">
        <img src="images/branding/wallpapers/fp_generic_thumb.png">
        <b>Generic</b>
        <div class="branding-downloads">
            <div class="branding-left">SD:</div>
            <div class="branding-right">
                <a href="images/branding/wallpapers/fp_generic_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_generic_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_generic_1600x1200.png">1600x1200</a>
            </div>
            <div class="branding-left">HD:</div>
            <div class="branding-right">
                <a href="images/branding/wallpapers/fp_generic_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_generic_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_generic_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>

    <div class="branding-item">
        <img src="images/branding/wallpapers/fp_shadow_thumb.png">
        <b>Shadow</b>
        <div class="branding-downloads">
            <div class="branding-left">SD:</div>
            <div class="branding-right">
                <a href="images/branding/wallpapers/fp_shadow_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_shadow_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_shadow_1600x1200.png">1600x1200</a>
            </div>
            <div class="branding-left">HD:</div>
            <div class="branding-right">
                <a href="images/branding/wallpapers/fp_shadow_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_shadow_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_shadow_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>

    <div class="branding-item">
        <img src="images/branding/wallpapers/fp_retro_thumb.png">
        <b>Retrowave</b>
        <div class="branding-downloads">
            <div class="branding-left">SD:</div>
            <div class="branding-right">
                <a href="images/branding/wallpapers/fp_retro_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_retro_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_retro_1600x1200.png">1600x1200</a>
            </div>
            <div class="branding-left">HD:</div>
            <div class="branding-right">
                <a href="images/branding/wallpapers/fp_retro_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_retro_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_retro_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>
</div>

<span class="title-small"><?= t('Banners_Title') ?></span>
<hr>

<div class="branding-container">
    <div class="branding-item">
        <img src="images/branding/banners/fp_banner_small.png">
        <b>Small</b>
        <div class="branding-download">
            <a href="images/branding/banners/fp_banner_small.png">96x32</a>
        </div>
    </div>

    <div class="branding-item">
        <img src="images/branding/banners/fp_banner_large.png">
        <b>Large</b>
        <div class="branding-download">
            <a href="images/branding/banners/fp_banner_large.png">192x64</a>
        </div>
    </div>
    
    <div class="branding-item">
        <img src="images/branding/banners/fp_banner_retro.png" width="128">
        <b>Retro</b>
        <div class="branding-download">
            <a href="images/branding/banners/fp_banner_retro.png">440x155</a>
        </div>
    </div>
</div>