<span class="title"><?= t('Branding_Title') ?></span>
<hr class="title-divider">

<div class="right">
    <img width="256" src="images/branding/designs.png">
</div>

<?= t('Branding_Para1') ?><br>

<?= t('Branding_Para2') ?><br>

<?= t('Branding_Para3') ?><br>

<span class="title-small"><?= t('Wallpapers_Title') ?></span>
<hr>

<?= t('Rain_Credit') ?>

<div class="wallpaper-container">
    <div class="wallpaper-item">
        <img src="images/branding/wallpapers/fp_generic_thumb.png">
        <b>Generic</b>
        <div class="wallpaper-download">
            <div class="wallpaper-left">SD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_generic_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_generic_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_generic_1600x1200.png">1600x1200</a>
            </div>
            <div class="wallpaper-left">HD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_generic_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_generic_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_generic_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>

    <div class="wallpaper-item">
        <img src="images/branding/wallpapers/fp_shadow_thumb.png">
        <b>Shadow</b>
        <div class="wallpaper-download">
            <div class="wallpaper-left">SD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_shadow_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_shadow_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_shadow_1600x1200.png">1600x1200</a>
            </div>
            <div class="wallpaper-left">HD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_shadow_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_shadow_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_shadow_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>

    <div class="wallpaper-item">
        <img src="images/branding/wallpapers/fp_retro_thumb.png">
        <b>Retrowave</b>
        <div class="wallpaper-download">
            <div class="wallpaper-left">SD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_retro_800x600.png">800x600</a>
                <a href="images/branding/wallpapers/fp_retro_1024x768.png">1024x768</a>
                <a href="images/branding/wallpapers/fp_retro_1600x1200.png">1600x1200</a>
            </div>
            <div class="wallpaper-left">HD:</div>
            <div class="wallpaper-right">
                <a href="images/branding/wallpapers/fp_retro_1280x720.png">1280x720</a>
                <a href="images/branding/wallpapers/fp_retro_1920x1080.png">1920x1080</a>
                <a href="images/branding/wallpapers/fp_retro_3840x2160.png">3840x2160</a>
            </div>
        </div>
    </div>
</div>