<span class="title"><?= t('Discord_Title') ?></span>
<hr class="title-divider">
<?= t('Discord_Intro', '<i>') ?>
<div class="border">
    <ol>
        <li> <?= t('Discord_Rule1', '<a href="https://discord.com/terms">', '<a href="https://discord.com/terms">') ?> </li>
        <li> <?= t('Discord_Rule2') ?> </li>
        <li> <?= t('Discord_Rule3') ?> </li>
        <li> <?= t('Discord_Rule4') ?> </li>
        <li> <?= t('Discord_Rule5', '<b>', '<b>', '<u>') ?> </li>
        <li> <?= t('Discord_Rule6', '<b>', '<i>', '<i>', '<i>') ?> </li>
        <li> <?= t('Discord_Rule7', '<i>') ?> </li>
        <li> <?= t('Discord_Rule8') ?> </li>
        <li> <?= t('Discord_Rule9') ?> </li>
        <li> <?= t('Discord_Rule10') ?> </li>
        <li> <?= t('Discord_Rule11') ?> </li>
    </ol>
</div>
<a href="https://discord.gg/qhvAkhWXU5"><?= t('Discord_Agreed') ?></a>
