<span class="title"><?= t('Discord_Title') ?></span>
<hr class="title-divider">
<?= t('Discord_Intro') ?><br>
<div class="border">
    <ol>
        <li> <?= t('Discord_Rule1') ?> </li>
        <li> <?= t('Discord_Rule2') ?> </li>
        <li> <?= t('Discord_Rule3') ?> </li>
        <li> <?= t('Discord_Rule4') ?> </li>
        <li> <?= t('Discord_Rule5') ?> </li>
        <li> <?= t('Discord_Rule6') ?> </li>
        <li> <?= t('Discord_Rule7') ?> </li>
        <li> <?= t('Discord_Rule8') ?> </li>
    </ol>
    <?= t('Discord_Curation_Exception') ?><br>

    <?= t('Discord_Sanctions') ?>
</div>
<a href="http://discord.gg/S9uJ794"><?= t('Discord_Agreed') ?></a>
