<span class="title"><?= t('Discord_Title') ?></span>
<hr class="title-divider">
<?= t('Discord_Intro', '<i>') ?>
<div class="border">
    <ol>
        <li> <?= t('Discord_Rule1', '<a href="https://discordapp.com/terms">', '<a href="https://discordapp.com/terms">') ?> </li>
        <li> <?= t('Discord_Rule2') ?> </li>
        <li> <?= t('Discord_Rule3') ?> </li>
        <li> <?= t('Discord_Rule4') ?> </li>
        <li> <?= t('Discord_Rule5', '<span style="text-decoration: underline">') ?> </li>
        <li> <?= t('Discord_Rule6') ?> </li>
        <li> <?= t('Discord_Rule7', '<i>') ?> </li>
        <li> <?= t('Discord_Rule8') ?> </li>
    </ol>
    <?= t('Discord_Curation_Exception') ?>
    <div class="break-medium"></div>
    <?= t('Discord_Sanctions') ?>
</div>
<a href="https://discord.gg/pbeUXW6B68"><?= t('Discord_Agreed') ?></a>
