<span class="title"><?= t('Downloads_Title') ?></span>
<hr class="title-divider">
<?= t('Downloads_Para1', '<a href="changelog.txt">') ?>
<div class="break-medium"></div>
<?= t('Downloads_Para2', '<b>') ?>
<div class="break-large"></div>

<span class="title-small"><?= t('Downloads_Software_Title') ?></span>
<hr>
<a class="title-small download-installer" href="FlashpointInstaller.exe"><img src="images/installer.png"><?= t('Downloads_Software_Download') ?></a>
<div class="break-medium"></div>
<div class="download-info">
    <?= t('Downloads_Software_Size', '<b>', '1.9MB') ?>
    <div class="break-min"></div>
    <?= t('Downloads_Software_Requirements', '<b>', '<a href="datahub/Mac_Support">', '<a href="datahub/Linux_Support">') ?>
    <div class="break-min"></div>
    <?= t('Downloads_Software_Hash', '<b>', '<code>', '9726c2a4482412b4ef568465c384610944ac282945f7a11f9c54307b90269371') ?>
</div>
<div class="break-medium"></div>

<?= t('Downloads_Software_Para1', '<b>', '<a href="source">') ?>
<div class="break-medium"></div>
<?= t('Downloads_Software_Para2', '<i>', '<a href="Flashpoint%20Core%2011.7z">', '<a href="datahub/Curation_Tutorial">') ?>
<div class="break-medium"></div>
<?= t('Downloads_Software_Para3', '<b>', '<a href="datahub/Troubleshooting_Antivirus_Interference">', '<a href="faq#security-concerns">') ?>
<div class="break-large"></div>

<span class="title-small"><?= t('Downloads_Archive_Title') ?></span>
<hr>
<?= t('Downloads_Archive_Para1', '<a href="https://unstable.life/flashpoint-database/downloads/">') ?>
<div class="break-medium"></div>
<b><?= t('Downloads_Archive_Para2') ?></b>
<div class="break-large"></div>

<hr>
<?= t('Downloads_Footer', '<a href="faq">', '<a href="discord">') ?>