<div class="download-avast"><?= t('Downloads_Avast', '<a href="datahub/Troubleshooting_Antivirus_Interference">') ?></div>

<span class="title"><?= t('Downloads_Title') ?></span>
<hr class="title-divider">

<?= t('Downloads_Description', '<b>', '<a href="source">', '<a href="faq">', '<a href="discord">') ?>
<div class="break-large"></div>
<hr>
<div class="break-large"></div>

<div class="download-container">
    <div class="download-item infinity">
        <div class="title-small download-title">
            <img src="images/package.png">
            <?= t('Downloads_Infinity_Title', '12') ?>
        </div>
        <div class="break-medium"></div>
        <div class="download-info">
            <?= t('Downloads_Infinity_Size', '<b>', '1.9MB', '~1-3GB') ?>
        </div>
        <div class="break-medium"></div>
        <div class="download-description">
            <?= t('Downloads_Infinity_Para1') ?>
            <div class="break-medium"></div>
            <?= t('Downloads_Infinity_Para2') ?>
        </div>
        <div class="break-medium"></div>
        <div class="download-links">
            <a class="download-link-main" href="https://github.com/FlashpointProject/FlashpointComponentTools/releases/download/1.0-rc8/FlashpointInstaller.exe">
                <?= t('Downloads_Infinity_Link') ?>
            </a>
            <div class="break-min"></div>
            <a class="download-link-alt" href="">
                <?= t('Downloads_Infinity_Link2') ?>
            </a>
        </div>
    </div>
    <div class="download-item ultimate">
        <div class="title-small download-title">
            <img src="images/package.png">
            <?= t('Downloads_Ultimate_Title', '11.1') ?>
        </div>
        <div class="break-medium"></div>
        <div class="download-info">
            <?= t('Downloads_Ultimate_Size', '<b>', '2TB', '3TB') ?>
        </div>
        <div class="break-medium"></div>
        <div class="download-description">
            <?= t('Downloads_Ultimate_Para1') ?>
            <div class="break-medium"></div>
            <?= t('Downloads_Ultimate_Para2', '<a href="https://www.qbittorrent.org/">', '<a href="https://7-zip.org/">') ?>
        </div>
        <div class="break-medium"></div>
        <div class="download-links">
            <a class="download-link-main" href="https://download.unstable.life/static/Flashpoint%252011.1%2520Ultimate.7z.torrent">
                <?= t('Downloads_Ultimate_Link') ?>
            </a>
            <div class="break-min"></div>
            <a class="download-link-alt" href="https://archive.org/details/Flashpoint11.1">
                <?= t('Downloads_Ultimate_Link2') ?>
            </a>
        </div>
    </div>
</div>

<div class="break-medium"></div>
<div class="download-requirements">
    <?= t('Downloads_Requirements', '<b>', '<a href="datahub/Mac_Support">', '<a href="datahub/Linux_Support">') ?>
    <div class="break-small"></div>
    <?= t('Downloads_Prerequisites', '<b>', '<a href="https://www.microsoft.com/en-us/download/details.aspx?id=48145">', '<a href="https://dotnet.microsoft.com/download/dotnet-framework/net47">') ?>
</div>

<div class="break-large"></div>
<hr>
<?= t('Downloads_Footer', '<a href="news">') ?>