<span class="title"><?= t('FAQ_Title') ?></span>
<hr class="title-divider">

<b><?= t('FAQ_Question1') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer1') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question2') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer2') ?>
<div class="break-large"></div>

<b id="security-concerns"><?= t('FAQ_Question3') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer3', '<a href="source">', '<a href="datahub/Troubleshooting_Antivirus_Interference">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question4') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer4', '150,000', '25,000', '<a href="https://flashpointproject.github.io/flashpoint-database/search/">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question5') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer5', '<a href="https://flashpointproject.github.io/flashpoint-database/statistics/">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question6') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer6', '<a href="http://www.nitrome.com/all-games/">', '<a href="http://www.nitrome.com/html5-games/">', '<b>') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question7') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer7', '<a href="datahub/Requesting_Content_For_Archival">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question8') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer8', '<a href="datahub/Curation_Tutorial">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question9') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer9', '<a href="discord">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question11') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer11', '<a href = "https://creativecommons.org/licenses/by/4.0/">', '<a href = "images/branding/logo_sources.7z">') ?>
<div class="break-large"></div>

<b id="donations"><?= t('FAQ_Question12') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer12', '<a href="https://opencollective.com/flashpointarchive">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question13') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer13', '<a href="https://flashpointproject.github.io/manual/?page=Troubleshooting">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question14') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer14', '<a href="contact">') ?>
<div class="break-large"></div>

<b><?= t('FAQ_Question15') ?></b>
<div class="break-small"></div>
<?= t('FAQ_Answer15', '<a href="datahub/Extended_FAQ">') ?>
