<span class="title">Frequently Asked Questions</span>
<hr class="title-divider">

<b>Who/what is BlueMaxima?</b><br>
BlueMaxima, or Ben Latimore is the Aussie who started Flashpoint and handles the master copies. No business or organization is involved with Flashpoint - it is a wholly community-run project.
<br style="margin-bottom:22px">

<b>What operating systems do you support?</b><br>
Flashpoint supports Windows 7 SP1 and newer (excluding stock Windows 8). Mac and Linux versions are constantly in flux due to technology changing left and right in the Windows version and a lack of dedicated maintainers; for the most up-to-date information, you'll have to ask on the Discord.
<br style="margin-bottom:22px">

<b id="security-concerns">Does Flashpoint pose any security concerns?</b><br>
Not that we know of. The entirety of our application suite (minus Infinity's game-downloading tech) can't connect to the open internet; any registry changes made by Flashpoint Secure Player are removed once the game is closed; all incoming curations are passed through a PC with competent and up-to-date antivirus software; and most importantly, the launcher and all of Flashpoint's inner workings are open-source and can be found <a href="https://github.com/FlashpointProject/">here</a>. We've done our best to ensure the collection is as safe as it can be, but despite our efforts, certain antiviruses such as Avast and AVG tend to detect important components as being dangerous. If you're affected by this issue, <a href="../datahub/Troubleshooting_Antivirus_Interference">read this page</a> for troubleshooting instructions.
<br style="margin-bottom:22px">

<b>How many games/animations are there?</b><br>
As of Flashpoint 10.1, we have over 100,000 games and 10,000 animations. You can search the collection without use of the launcher <a href="https://nul.sh/misc/flashpoint/">here</a>. Alternatively, you can view the respective lists <a href="../datahub/Game_Master_List">here</a> and <a href="../datahub/Animation_Master_List">here</a>.
<br style="margin-bottom:22px">

<b>What platforms does the collection offer?</b><br>
We support games and animations running on every platform listed at the <a href="../platforms">Supported Platforms</a> page.
<br style="margin-bottom:22px">

<b>Where are the Nitrome games?</b><br>
Nitrome politely asked us to remove their content from the collection. If you're looking to play their games, do so at their <a href="http://www.nitrome.com/all-games/">website</a>, and if Flash isn't an option, follow their growing <a href="http://www.nitrome.com/html5-games/">HTML5-compatible catalog</a>. <b>Flashpoint does not condone harassment over Nitrome's decision.</b>
<br style="margin-bottom:22px">

<b>How can I request a game/animation?</b><br>
You can make a request by first reading <a href="../datahub/Requesting_Content_For_Archival">this article</a> all the way through, then following the links at the bottom.
<br style="margin-bottom:22px">

<b>Can I add a game/animation myself?</b><br>
Yes. Follow the instructions listed in the <a href="../datahub/Curation_Tutorial">curation tutorial</a> to set up your curator audition. Once it's accepted, you can submit as many more curations as you desire.
<br style="margin-bottom:22px">

<b>I want to contribute in some other way (coding, testing, etc). How can I help?</b><br>
Join our <a href="../discord">Discord server</a> for more details. The majority of our work & communication happens there.
<br style="margin-bottom:22px">

<b>Is Flashpoint open source?</b><br>
Yes...ish. The sources for our custom-made tech such as the launcher are all available at our <a href="https://github.com/FlashpointProject/">GitHub</a>. The sources for the software we include in Flashpoint are available from their respective websites (we don't modify the source of any of the software we include). The binaries for the web plugins themselves aren't open source, but if they were, we wouldn't be here to begin with.
<br style="margin-bottom:22px">

<b>Can I use the logo/is it available under Creative Commons?</b><br>
Yes - the logo falls under the <a href = "https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a> license. For attribution, you may optionally credit Seirade and BlueMaxima's Flashpoint. Source files can be found <a href = "images/branding/logo_sources.7z">here</a>.
<br style="margin-bottom:22px">

<b>Where can I donate to the project?</b><br>
Out of respect for the artists and developers whose works can be found in Flashpoint, we try to avoid soliciting donations. While we previously ran <a href="https://gogetfunding.com/help-us-secure-funding-for-the-hosting-of-bluemaximas-flashpoint/">a fundraiser</a> to cover server costs, we have no plans to launch another one in the future.
<br style="margin-bottom:22px">

<b>Flashpoint isn't working correctly!</b><br>
Follow the troubleshooting steps listed in the <a href="https://flashpointproject.github.io/manual/Troubleshooting.html">manual</a>. If you're still having problems afterwards, ask for help in our Discord.
<br style="margin-bottom:22px">

<b>I want a game/animation removed from Flashpoint for one reason or another.</b><br>
Alert us, either via our Discord or <a href="../contact/">directly by email</a>. We'll probably try to convince you to let us keep your game in for historical sake, but we aren't unreasonable.
<br style="margin-bottom:22px">

<b>I have another question.</b><br>
Consult our <a href="../datahub/Extended_FAQ">extended FAQ.</a> If your question isn't answered there, join our Discord.
