<span class="title"><?= t('FAQ_Title') ?></span>
<hr class="title-divider">

<b><?= t('FAQ_Question1') ?></b><br>
<?= t('FAQ_Answer1') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question2') ?></b><br>
<?= t('FAQ_Answer2') ?>
<br style="margin-bottom:22px">

<b id="security-concerns"><?= t('FAQ_Question3') ?></b><br>
<?= t('FAQ_Answer3') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question4') ?></b><br>
<?= t('FAQ_Answer4') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question5') ?></b><br>
<?= t('FAQ_Answer5') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question6') ?></b><br>
<?= t('FAQ_Answer6') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question7') ?></b><br>
<?= t('FAQ_Answer7') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question8') ?></b><br>
<?= t('FAQ_Answer8') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question9') ?></b><br>
<?= t('FAQ_Answer9') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question10') ?></b><br>
<?= t('FAQ_Answer10') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question11') ?></b><br>
<?= t('FAQ_Answer11') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question12') ?></b><br>
<?= t('FAQ_Answer12') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question13') ?></b><br>
<?= t('FAQ_Answer13') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question14') ?></b><br>
<?= t('FAQ_Answer14') ?>
<br style="margin-bottom:22px">

<b><?= t('FAQ_Question15') ?></b><br>
<?= t('FAQ_Answer15') ?>
