<span class="title"><?= t('About_Welcome') ?></span>
<hr class="title-divider">
<div class="home-media right">
    <iframe src="https://www.youtube.com/embed/rUatW8cXl-s" frameborder="0" allowfullscreen></iframe>
</div>

<?= t('About_Title') ?><br>

<?= t('About_Para1') ?><br>

<?= t('About_Para2') ?><br>

<div class="home-media left">
    <a href="images/launcher.png"><img src="images/launcher.png"></a>
</div>

<?= t('About_Para3') ?><br>

<?= t('About_Para4') ?><br>

<?= t('About_Para5') ?>

<div class="home-download">
    <a href="downloads"><img src="images/image-translations/download/<?= t('Lang_Code') ?>.svg"></a><br style="margin-bottom:4px">
    <b><a href="https://unstable.life/flashpoint-database/search/"><?= t('Search_Collection') ?></a> - <a href="datahub/Requesting_Content_For_Archival"><?= t('Request_Archival') ?></a></b>
</div>
