<span class="title"><?= t('About_Welcome') ?></span>
<hr class="title-divider">
<div class="home-media right">
    <iframe src="https://www.youtube.com/embed/rUatW8cXl-s" frameborder="0" allowfullscreen></iframe>
</div>

<?= t('About_Title') ?>
<div class="break-large"></div>

<?= t('About_Para1', '<a href="https://flashpointproject.github.io/flashpoint-database/statistics/">', '170,000', '71') ?>
<div class="break-large"></div>

<?= t('About_Para2', '<a href="https://github.com/FlashpointProject/launcher">', '<a href="https://github.com/FlashpointProject/FlashpointProxy">', '<a href="https://github.com/FlashpointProject/FlashpointSecureTools">', '<a href="source">') ?>
<div class="break-large"></div>

<div class="home-media left">
    <a href="images/launcher.png"><img src="images/launcher_thumb.png"></a>
</div>

<?= t('About_Para3', '<a href="news#starting-date">') ?>
<div class="break-large"></div>

<?= t('About_Para4', '<a href="https://opencollective.com/flashpointarchive">') ?>

<div class="home-download">
    <a href="downloads"><img src="images/image-translations/download/<?= t('Lang_Code') ?>.svg"></a>
    <div class="break-small"></div>
    <b><a href="https://flashpointproject.github.io/flashpoint-database/search/"><?= t('Search_Collection') ?></a> - <a href="datahub/Requesting_Content_For_Archival"><?= t('Request_Archival') ?></a></b>
</div>
