<span class="title">Welcome</span>
<hr class="title-divider">
<div class="home-media right">
    <iframe src="https://www.youtube.com/embed/rUatW8cXl-s" frameborder="0" allowfullscreen></iframe>
</div>

BlueMaxima's Flashpoint is a webgame preservation project.<br>

Internet history and culture is important, and content made on web platforms including, but not limited to Adobe Flash, make up a significant portion of that culture. This project is dedicated to preserving as many experiences from these platforms as possible, so that they aren't lost to time. Since early 2018, Flashpoint has saved more than 100,000 games and 10,000 animations running on 35 different platforms.<br>

Flashpoint was started in January 2018 by BlueMaxima in an attempt to outrun the disappearance of content prior to the death of Flash. It has since evolved into an international project involving over 100 community contributors, encompassing both webgames and animations created for numerous internet plugins, frameworks, and standards.<br>

<div class="home-media left">
    <a href="images/launcher.png"><img src="images/launcher.png"></a>
</div>

Flashpoint utilizes a strong selection of open-source software. By combining the power of Apache, a custom-built launcher, and our own application called the Flashpoint Secure Player, we can play web-based media in a quick, user-friendly environment without leaving permanent changes or security holes on your computer.<br>

We offer two versions of the software; Ultimate, which contains every piece of media in an offline ready format, and Infinity, a smaller distribution that allows you to download and play content at will. Both  versions are unaffected by the end of support for Flash and other plugins.<br>

This project is and will always be entirely non-profit, to preserve the sense of community and sharing that came with Flash and its ilk. To learn more about Flashpoint, refer to the sidebar on the left of the page.

<div class="home-download">
    <a href="downloads"><img src="images/download.svg"></a><br style="margin-bottom:4px">
    <b><a href="https://nul.sh/misc/flashpoint/">Search the Collection</a> - <a href="datahub/Requesting_Content_For_Archival">Request Content for Archival</a></b>
</div>
