<!DOCTYPE html>
<html>
    <head>
        <title><?= ${basename(__FILE__, '.phtml').'_title'} ?></title>
        <base href="/flashpoint/" />
        <link rel="icon" href="images/favicon.svg">
        <?php foreach (self::$cssFiles as $cssFile) : ?>
            <link rel="stylesheet" type="text/css" href="css/<?= $cssFile ?>.css">
        <?php endforeach ?>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="Content-Language" content="en">
        <meta name="viewport" content="width=device-width" />
        <meta name="description" content="<?= ${basename(__FILE__, '.phtml').'_description'} ?>">
        <meta name="keywords" content="<?= ${basename(__FILE__, '.phtml').'_keywords'} ?>">
        <meta name="author" content="BlueMaxima">
    </head>
    <body>
        <div class="page-container">
            <div class="header">
                <div class="sidebar">
                    <a href="" title="Home"><img src="images/logo.svg"></a>
                    <div class="sidebar-links">
                        <input type="checkbox">
                        <a><div><?= $selectedLanguage ?></div><div>▶&#xFE0E;</div></a>
                        <div class="language-select sidebar-links">
                            <?php foreach ($availableLanguages as $code => $name) : ?>
                                <a href="<?= $url ?>?lang=<?= $code ?>"><div><?= $name ?></div></a>
                            <?php endforeach ?>
                        </div>
                        <div class="break-medium"></div>
                        <a href="./"><div><?= t('Home') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="news"><div><?= t('News') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="faq"><div><?= t('FAQ') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="downloads"><div><?= t('Downloads') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="source"><div><?= t('Source') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="branding"><div><?= t('Branding') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="contact"><div><?= t('Contact') ?></div><div>◀&#xFE0E;</div></a>
                        <div class="break-medium"></div>
                        <a href="https://unstable.life/flashpoint-database/"><div><?= t('Database') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="https://flashpointproject.github.io/manual/"><div><?= t('Manual') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="datahub"><div><?= t('Wiki') ?></div><div>◀&#xFE0E;</div></a>
                        <a href="discord"><div>Discord</div><div>◀&#xFE0E;</div></a>
                        <a href="https://twitter.com/fp_archive"><div>Twitter</div><div>◀&#xFE0E;</div></a>
                    </div>
                    <img src="images/pixels.svg">
                </div>
                <div class="header-wordmark">
                    <a href="" title="Home"><img src="images/textlogo.svg"></a>
                </div>
                <div class="header-mosaic">
                    <img src="images/mosaic.png">
                </div>
            </div>
            <div class="content">
                <?php require $this->getNextView(); ?>
            </div>
        </div>
    </body>
</html>
