<span class="title"><?= t('News_Title') ?></span>
<hr class="title-divider">

<?= t('News_Para1') ?>
<div class="break-medium"></div>
<?= t('News_Para2', '<a href="changelog.txt">', '<a href="https://archive.org/details/@bluemaxima">', '<a href="https://archive.org/details/@dri0m">') ?>

<div class="border">
    <div class="news-date">2023-07-10</div>
    Flashpoint 12, <i title="<?= t('News_Flashpoint_12_Meta') ?>"><?= t('News_Flashpoint_12') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2023-01-13</div>
    Flashpoint 11.1, <i title="<?= t('News_Flashpoint_11_1_Meta') ?>"><?= t('News_Flashpoint_11_1') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.
    
    <hr class="news-divider">
    
    <div class="news-date">2022-08-20</div>
    Flashpoint 11, <i title="<?= t('News_Flashpoint_11_Meta') ?>"><?= t('News_Flashpoint_11') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2021-10-02</div>
    Flashpoint 10.1, <i title="<?= t('News_Flashpoint_10_1_Meta') ?>"><?= t('News_Flashpoint_10_1') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2021-05-10</div>
    Flashpoint 10, <i title="<?= t('News_Flashpoint_10_0_Meta') ?>"><?= t('News_Flashpoint_10_0') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2021-04-01</div>
    <?= t('News_Flashpoint_Update_April_2021', '<a href="https://www.youtube.com/watch?v=sC3Vbd7_WxI">') ?>

    <hr class="news-divider">

    <div class="news-date">2020-11-17</div>
    Flashpoint 9.0, <i title="<?= t('News_Flashpoint_9_0_Meta') ?>"><?= t('News_Flashpoint_9_0') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2020-08-28</div>
    Flashpoint 8.2, <i title="<?= t('News_Flashpoint_8_2_Meta') ?>"><?= t('News_Flashpoint_8_2') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2020-08-01</div>
    <?= t('News_Flashpoint_Update_August_2020', '<a href="https://link.medium.com/MflJBqYNI8">') ?>

    <hr class="news-divider">

    <div class="news-date">2020-07-01</div>
    Flashpoint 8.1, <i title="<?= t('News_Flashpoint_8_1_Meta') ?>"><?= t('News_Flashpoint_8_1') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2020-05-30</div>
    <?= t('News_Flashpoint_Update_June_2020', '<a href="https://link.medium.com/JXuT3ZLfv7">') ?>

    <hr class="news-divider">

    <div class="news-date">2020-04-30</div>
    Flashpoint 8.0, <i title="<?= t('News_Flashpoint_8_0_Meta') ?>"><?= t('News_Flashpoint_8_0') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2020-03-30</div>
    <?= t('News_Flashpoint_Update_April_2020', '<a href="https://link.medium.com/7MDO0c0fv7">') ?>

    <hr class="news-divider">

    <div class="news-date">2020-03-01</div>
    <?= t('News_Flashpoint_Update_March_2020', '<a href="https://link.medium.com/TJtvYbFgv7">') ?>

    <hr class="news-divider">

    <div class="news-date">2020-02-01</div>
    <a href="https://kotaku.com/over-36-000-flash-games-have-been-saved-and-are-now-pla-1841389493"><?= t('News_Featured_Kotaku_Link') ?></a> <?= t('News_Featured_Kotaku_Rest') ?>

    <hr class="news-divider">

    <div class="news-date">2020-01-27</div>
    Flashpoint 7.1, <i title="<?= t('News_Flashpoint_7_1_Meta') ?>"><?= t('News_Flashpoint_7_1') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-12-22</div>
    Flashpoint 7.0, <i title="<?= t('News_Flashpoint_7_0_Meta') ?>"><?= t('News_Flashpoint_7_0') ?></i>, <?= t('News_Is_Available') ?> <?= t('News_Grab_Download', '<a href="downloads">') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-11-30</div>
    <?= t('News_Flashpoint_Update_November_2019', '<a href="https://link.medium.com/nZwgq6Chv7">') ?>

    <hr class="news-divider">

    <div class="news-date">2019-10-30</div>
    <?= t('News_Flashpoint_Update_October_2019', '<a href="https://link.medium.com/ZUAVj9rDw7">') ?>

</div>

<span class="title-small"><?= t('News_Old_Releases_Title') ?></span>
<hr class="title-divider">

<?= t('News_Old_Releases_Description') ?>

<div class="border">

    <div class="news-date">2019-09-28</div>
    Flashpoint 6.3, <i title="<?= t('News_Flashpoint_6_3_Meta') ?>"><?= t('News_Flashpoint_6_3') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-07-22</div>
    Flashpoint 6.2, <i title="<?= t('News_Flashpoint_6_2_Meta') ?>"><?= t('News_Flashpoint_6_2') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-05-30</div>
    Flashpoint 6.1, <i title="<?= t('News_Flashpoint_6_1_Meta') ?>"><?= t('News_Flashpoint_6_1') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-04-26</div>
    Flashpoint 6.0, <i title="<?= t('News_Flashpoint_6_0_Meta') ?>"><?= t('News_Flashpoint_6_0') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-02-27</div>
    Flashpoint 5.5, <i title="<?= t('News_Flashpoint_5_5_Meta') ?>"><?= t('News_Flashpoint_5_5') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-01-29</div>
    Flashpoint 5.4.1, <i title="<?= t('News_Flashpoint_5_4_1_Meta') ?>"><?= t('News_Flashpoint_5_4_1') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2019-01-29</div>
    Flashpoint 5.4, <i title="<?= t('News_Flashpoint_5_4_Meta') ?>"><?= t('News_Flashpoint_5_4') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-12-23</div>
    Flashpoint 5.3, <i title="<?= t('News_Flashpoint_5_3_Meta') ?>"><?= t('News_Flashpoint_5_3') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-11-26</div>
    Flashpoint 5.2, <i title="<?= t('News_Flashpoint_5_2_Meta') ?>"><?= t('News_Flashpoint_5_2') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-10-27</div>
    Flashpoint 5.1, <i title="<?= t('News_Flashpoint_5_1_Meta') ?>"><?= t('News_Flashpoint_5_1') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-09-28</div>
    Flashpoint 5.0, <i title="<?= t('News_Flashpoint_5_0_Meta') ?>"><?= t('News_Flashpoint_5_0') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-08-28</div>
    Flashpoint 4.1, <i title="<?= t('News_Flashpoint_4_1_Meta') ?>"><?= t('News_Flashpoint_4_1') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-08-12</div>
    Flashpoint 4.0, <i title="<?= t('News_Flashpoint_4_0_Meta') ?>"><?= t('News_Flashpoint_4_0') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-07-17</div>
    Flashpoint 3.3, <i title="<?= t('News_Flashpoint_3_3_Meta') ?>"><?= t('News_Flashpoint_3_3') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-06-27</div>
    Flashpoint 3.2, <i title="<?= t('News_Flashpoint_3_2_Meta') ?>"><?= t('News_Flashpoint_3_2') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-06-09</div>
    Flashpoint 3.1, <i title="<?= t('News_Flashpoint_3_1_Meta') ?>"><?= t('News_Flashpoint_3_1') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-05-30</div>
    Flashpoint 3.0, <i title="<?= t('News_Flashpoint_3_0_Meta') ?>"><?= t('News_Flashpoint_3_0') ?></i>, <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-05-14</div>
    Flashpoint 2.0 <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-05-05</div>
    Flashpoint 1.4 <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-05-02</div>
    Flashpoint 1.3.2 <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-05-01</div>
    Flashpoint 1.3.1 <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-04-30</div>
    Flashpoint 1.3 <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-04-22</div>
    Flashpoint 1.2 <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-04-13</div>
    Flashpoint 1.1 <?= t('News_Was_Released') ?>.

    <hr class="news-divider">

    <div class="news-date">2018-??-??</div>
    <?= t('News_Flashpoint_1') ?>

    <hr class="news-divider">

    <div class="news-date">2018-01-15</div>
    <?= t('News_Flashpoint_0') ?>

    <hr class="news-divider">

    <div class="news-date" id="starting-date">2017-12-26</div>
    <?= t('News_Flashpoint_Started') ?>

</div>
