<span class="title"><?= t('Platforms_Title') ?></span>
<hr class="title-divider">
<?= t('Platforms_Description1') ?><br>
<?= t('Platforms_Description2') ?><br>
<div class="border">
    <img src="images/icons/3dgroove.png">
    <span class="title-small" id="3dgroove">3D Groove GX</span>
    <hr>
    <b><?= t('Platforms_By') ?> The Groove Alliance</b> | <b>2002-2009</b> | <b>33 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_The_Groove_Alliance_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/3dvia.png">
    <span class="title-small" id="3dvia">3DVIA Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Dassault Systèmes</b> | <b>1999-2016</b> | <b>210 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_3DVIA_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/aboutpeople.png">
    <span class="title-small" id="aboutpeople">AboutPeople</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>4 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_AboutPeople_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/abouttime.png">
    <span class="title-small" id="abouttime">AboutTime</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>4 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_AboutTime_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/alambik.png">
    <span class="title-small" id="alambik">Alambik Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Alambik Limited</b> | <b>2001-2004</b> | <b>198 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Alambik_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/animaflex.png">
    <span class="title-small" id="animaflex">AnimaFlex</span>
    <hr>
    <b><?= t('Platforms_By') ?> RubberFlex Software</b> | <b>1997</b> | <b>20 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_AnimaFlex_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/activex.png">
    <span class="title-small" id="activex">ActiveX Controls</span>
    <hr>
    <b><?= t('Platforms_By') ?> Microsoft</b> | <b>1996-Present</b> | <b>106 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_ActiveX_Controls_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/atmosphere.png">
    <span class="title-small" id="atmosphere">Adobe Atmosphere Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Attitude Software, Adobe</b> | <b>1998-2000 & 2001-2005</b> | <b>126 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Adobe_Atmosphere_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/flash.png">
    <span class="title-small" id="flash">Adobe Flash Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> FutureWave, Macromedia, Adobe</b> | <b>1996-2020</b> | <b>132,219 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Adobe_Flash_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/shockwave.png">
    <span class="title-small" id="shockwave">Adobe Shockwave Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Macromedia, Adobe</b> | <b>1995-2019</b> | <b>4,802 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Adobe_Shockwave_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/ambulant.png">
    <span class="title-small" id="ambulant">Ambulant</span>
    <hr>
    <b><?= t('Platforms_By') ?> Centrum Wiskunde & Informatica</b> | <b>2003-2016</b> | <b>8 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Ambulant_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/autodeskmapguide.png">
    <span class="title-small" id="autodeskmapguide">Argus/Autodesk MapGuide</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>1 <?= t('Platforms_Entry') ?></b><br>
    <?= t('Platforms_Argus_Autodesk_MapGuide_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/asapwebshow.gif"><img src="images/icons/harvardgraphicswebshow.png">
    <span class="title-small" id="asapwebshow">ASAP Webshow / Harvard Graphics WebShow</span>
    <hr>
    <b><?= t('Platforms_By') ?> Software Publishing Corporation / Serif</b> | <b>1996-1998 & 1998-2000</b> | <b>11 <?= t('Platforms_Entries') ?> & 3 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_ASAP_Webshow_Harvard_Graphics_WebShow_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/authorware.png">
    <span class="title-small" id="authorware">Authorware Web Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Macromedia, Adobe</b> | <b>1996-2007</b> | <b>120 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Authorware_Web_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/axel.png">
    <span class="title-small" id="axel">AXEL Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> MindAvenue</b> | <b>2002-2006</b> | <b>27 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_MindAvenue_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/bitplayer.png">
    <span class="title-small" id="bitplayer">BitPlayer</span>
    <hr>
    <b><?= t('Platforms_By') ?> BitMagic</b> | <b>1999-2001</b> | <b>57 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_BitPlayer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/blender.png">
    <span class="title-small" id="blender">Blender</span>
    <hr>
    <b><?= t('Platforms_By') ?> ???</b> | <b>???-???</b> | <b>6 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Blender_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/burster.png">
    <span class="title-small" id="burster">Burster</span>
    <hr>
    <b><?= t('Platforms_By') ?> iTechnologie Ldt.</b> | <b>2010-2016</b> | <b>12 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Burster_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/calendarquick.png">
    <span class="title-small" id="calendarquick">Calendar Quick Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Logic Pulse</b> | <b>1996-1999</b> | <b>12 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Calendar_Quick_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/cult3d.png">
    <span class="title-small" id="cult3d">Cult3D</span>
    <hr>
    <b><?= t('Platforms_By') ?> Cycore Computers, Cycore Systems AB</b> | <b>1999-2013</b> | <b>70 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Cult3D_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/dfusion.png">
    <span class="title-small" id="dfusion">D'Fusion @Home Web Plug-In</span>
    <hr>
    <b><?= t('Platforms_By') ?> Total Immersion</b> | <b>2009-2015</b> | <b>3 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_DFusion_Home_Web_PlugIn_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/dpgraph.png">
    <span class="title-small" id="dpgraph">DPGraph</span>
    <hr>
    <b><?= t('Platforms_By') ?> David Parker, DPGraph</b> | <b>1999-2019</b> | <b>22 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_DPGraph_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/eanimator.png">
    <span class="title-small" id="eanimator">E-アニメータ / SharpMotionART</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sharp Corporation</b> | <b>2001-2004</b> | <b>154 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_E_Animator_SharpMotionART_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/envoy.png">
    <span class="title-small" id="envoy">Envoy</span>
    <hr>
    <b><?= t('Platforms_By') ?> Tumbleweed Software Corp., Novell</b> | <b>1995-1999</b> | <b>37 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Envoy_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/eva.png">
    <span class="title-small" id="eva">EVA</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sharp Corporation</b> | <b>1997-2016</b> | <b>460 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_EVA_Description', '<b>', '<b>', '<b>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/flatlandrover.png">
    <span class="title-small" id="flatlandrover">Flatland Rover</span>
    <hr>
    <b><?= t('Platforms_By') ?> Flatland Online Inc.</b> | <b>1997-2005</b> | <b>20 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Flatland_Rover_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/formulaone.gif">
    <span class="title-small" id="formulaone">Formula One</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>11 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Formula_One_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/fractalviewer.png">
    <span class="title-small" id="fractalviewer">Fractal Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>5 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Fractal_Viewer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/freehand.png">
    <span class="title-small" id="freehand">FreeHand</span>
    <hr>
    <b><?= t('Platforms_By') ?> Macromedia</b> | <b>1996-1998</b> | <b>10 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_FreeHand_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/gobit.png">
    <span class="title-small" id="gobit">GoBit Games Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> GoBit Games</b> | <b>2008-2009</b> | <b>2 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_GoBit_Games_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/hotsauce.png">
    <span class="title-small" id="hotsauce">HotSauce</span>
    <hr>
    <b><?= t('Platforms_By') ?> Apple Inc.</b> | <b>1996-1997</b> | <b>6 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_HotSauce_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/html.png">
    <span class="title-small" id="html">HTML / HTML5</span>
    <hr>
    <b><?= t('Platforms_By') ?> World Wide Web Consortium, WHATWG</b> | <b>1993/1995/1997/2008-Present</b> | <b>18,374 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_HTML_HTML5_Description', '<b>', '<b>', '<b>', '<b>', '<i>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/hypercosm.png">
    <span class="title-small" id="hypercosm">Hypercosm Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Hypercosm, ORBITEC</b> | <b>1999-2016</b> | <b>127 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Hypercosm_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/hyperg.png">
    <span class="title-small" id="hyperg">Hyper-G</span>
    <hr>
    <b><?= t('Platforms_By') ?> Institut für Informationssysteme und Computer Medien (IICM)</b> | <b>1995-1996</b> | <b>7 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_HyperG_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/illuminatus.png">
    <span class="title-small" id="illuminatus">Illuminatus</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>3 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Illuminatus_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/ipix.png">
    <span class="title-small" id="ipix">iPix Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>36 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_iPix_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/java.png">
    <span class="title-small" id="java">Java Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sun Microsystems, Oracle</b> | <b>1995-2018</b> | <b>1,309 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Java_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/jcampdx.png">
    <span class="title-small" id="jxampdx">JCAMP-DX</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>1 <?= t('Platforms_Entry') ?></b><br>
    <?= t('Platforms_JCAMPDX_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/lightningstrike.png">
    <span class="title-small" id="lightningstrike">Lightning Strike</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>3 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Lightning_Strike_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/livemath.png">
    <span class="title-small" id="livemath">LiveMath Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Prescience Corporation, Waterloo Maple, MathMonkeys</b> | <b>1994-2014</b> | <b>125 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_LiveMath_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/livepictureviewer.png">
    <span class="title-small" id="livepictureviewer">Live Picture Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>2 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_XXX_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/mhsv.png">
    <span class="title-small" id="mhsv">MHSV</span>
    <hr>
    <b><?= t('Platforms_By') ?> ParaGraph International</b> | <b>1996</b> | <b>17 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_MHSV_Description', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/silverlight.png">
    <span class="title-small" id="silverlight">Microsoft Silverlight</span>
    <hr>
    <b><?= t('Platforms_By') ?> Microsoft</b> | <b>2007-2021</b> | <b>234 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Microsoft_Silverlight_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/noteworthycomposer.png">
    <span class="title-small" id="noteworthycomposer">NoteWorthy Composer Browser Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>7 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_NoteWorthy_Composer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/o2cplayer.png">
    <span class="title-small" id="o2cplayer">o2c-Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> mb Software AG, Eleco Software GmbH</b> | <b>1999-Present</b> | <b>8 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_O2C_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/octree.png">
    <span class="title-small" id="octree">Octree View</span>
    <hr>
    <b><?= t('Platforms_By') ?> Octree Corporation</b> | <b>1998-2007</b> | <b>9 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Octree_View_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/pixound.png">
    <span class="title-small" id="pixound">Pixound</span>
    <hr>
    <b><?= t('Platforms_By') ?> Hologramophone Research, Frankfurt Balkind Partners, Techné Media</b> | <b>1996-2005</b> | <b>6 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Pixound_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/deepv.png"><img src="images/icons/play3d.png">
    <span class="title-small" id="play3d">Play3D / DeepV</span>
    <hr>
    <b><?= t('Platforms_By') ?> Mark Carolan, Heads Off</b> | <b>1996-1997 & 1997-2001</b> | <b>1 <?= t('Platforms_Entry') ?> & 3 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Play3D_DeepV_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/pointplus.png">
    <span class="title-small" id="pointplus">PointPlus</span>
    <hr>
    <b><?= t('Platforms_By') ?> Net-Scene</b> | <b>1996-1997</b> | <b>11 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_PointPlus_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/popcap.png">
    <span class="title-small" id="popcap">PopCap Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> PopCap Games</b> | <b>2004-2007</b> | <b>12 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_PopCap_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/protoplay.png">
    <span class="title-small" id="protoplay">ProtoPlay</span>
    <hr>
    <b><?= t('Platforms_By') ?> Altia Inc.</b> | <b>1996-2009</b> | <b>12 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_ProtoPlay_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/pulse.png">
    <span class="title-small" id="pulse">Pulse Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Pulse Entertainment</b> | <b>1999-2003</b> | <b>12 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Pulse_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/rebol.png">
    <span class="title-small" id="rebol">REBOL Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> REBOL Technologies</b> | <b>2004-2006</b> | <b>59 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_REBOL_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/shiva3d.png">
    <span class="title-small" id="shiva3d">ShiVa Web Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> ShiVa Technologies</b> | <b>2004-2019</b> | <b>147 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_ShiVa_Web_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/showit.png">
    <span class="title-small" id="showit">Show It!</span>
    <hr>
    <b><?= t('Platforms_By') ?> Corel</b> | <b>1997-2001</b> | <b>5 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Show_It_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/smoothmovepanorama.png">
    <span class="title-small" id="smoothmovepanorama">SmoothMove Panorama</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>24 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_SmoothMove_Panorama_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/squeak.png">
    <span class="title-small" id="squeak">Squeak / Etoys</span>
    <hr>
    <b><?= t('Platforms_By') ?> Viewpoints Research Institute Inc.</b> | <b>2001-2012</b> | <b>18 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Squeak_Etoys_Description') ?>
	<br style="margin-bottom:20px">

    <img src="images/icons/viscape.png">
    <span class="title-small" id="viscape">Superscape Viscape</span>
    <hr>
    <b><?= t('Platforms_By') ?> Superscape</b> | <b>1996-2000</b> | <b>116 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Superscape_Viscape_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/surroundvideo.png">
    <span class="title-small" id="viscape">Surround Video</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>31 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Surround_Video_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/svfviewer.png">
    <span class="title-small" id="svfviewer">SVF viewer / Simple Vector Format Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>7 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_SVF_Viewer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/thingviewer.png">
    <span class="title-small" id="thingviewer">ThingViewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> Parable Corporation, ThingWorld</b> | <b>1997-2002</b> | <b>26 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_ThingViewer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/tcl.png">
    <span class="title-small" id="tcl">Tcl Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sun Microsystems, Scriptics, Tcl Core Team</b> | <b>1996-2006</b> | <b>73 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Tcl_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/unity.png">
    <span class="title-small" id="unity">Unity Web Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Unity Technologies</b> | <b>2005-2016</b> | <b>1,767 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Unity_Web_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/webmap.png">
    <span class="title-small" id="webmap">Visual WebMap</span>
    <hr>
    <b><?= t('Platforms_By') ?> Project Development</b> | <b>1997</b> | <b>5 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Visual_WebMap_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/vitalize.png">
    <span class="title-small" id="vitalize">Vitalize!</span>
    <hr>
    <b><?= t('Platforms_By') ?> Corel, Clickteam</b> | <b>1997-2012</b> | <b>737 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Vitalize_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/vrml.png">
    <span class="title-small" id="vrml">VRML</span>
    <hr>
    <b><?= t('Platforms_By') ?> Web3D Consortium</b> | <b>1994-2001</b> | <b>467 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_VRML_Description', '<b>', '<b>', '<b>', '<b>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/webanimator.png">
    <span class="title-small" id="webanimator">DeltaPoint WebAnimator</span>
    <hr>
    <b><?= t('Platforms_By') ?> DeltaPoint Inc.</b> | <b>??-??</b> | <b>8 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_DeltaPoint_WebAnimator_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/x3d.png">
    <span class="title-small" id="x3d">X3D / Extensible 3D Graphics</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b> | <b>10 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_X3D_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/xara.png">
    <span class="title-small" id="xara">Xara Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Xara Ltd</b> | <b>1996-2000</b> | <b>75 <?= t('Platforms_Entries') ?></b><br>
    <?= t('Platforms_Xara_Plugin_Description') ?>
</div>

<span class="title"><?= t('Platforms_Coming_Soon') ?></span>
<hr class="title-divider">
<?= t('Platforms_Coming_Soon_Description') ?>
<div class="border">
    <!-- TODO -->
</div>
