<span class="title"><?= t('Platforms_Title') ?></span>
<hr class="title-divider">
<?= t('Platforms_Description1', '<a href="https://unstable.life/flashpoint-database/statistics/">') ?><br>
<?= t('Platforms_Description2') ?><br>
<div class="border">
    <img src="images/icons/3dgroove.png">
    <span class="title-small">3D Groove GX</span>
    <hr>
    <b><?= t('Platforms_By') ?> The Groove Alliance</b> | <b>2002-2009</b><br>
    <?= t('Platforms_3D_Groove_GX_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/3dvia.png">
    <span class="title-small">3DVIA Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Dassault Systèmes</b> | <b>1999-2016</b><br>
    <?= t('Platforms_3DVIA_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/aboutpeople.png">
    <span class="title-small">AboutPeople</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_AboutPeople_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/abouttime.png">
    <span class="title-small">AboutTime</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_AboutTime_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/activex.png">
    <span class="title-small">ActiveX Controls</span>
    <hr>
    <b><?= t('Platforms_By') ?> Microsoft</b> | <b>1996-Present</b><br>
    <?= t('Platforms_ActiveX_Controls_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/atmosphere.png">
    <span class="title-small">Adobe Atmosphere Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Attitude Software, Adobe</b> | <b>1998-2000 & 2001-2005</b><br>
    <?= t('Platforms_Adobe_Atmosphere_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/flash.png">
    <span class="title-small">Adobe Flash Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> FutureWave, Macromedia, Adobe</b> | <b>1996-2020</b><br>
    <?= t('Platforms_Adobe_Flash_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/shockwave.png">
    <span class="title-small">Adobe Shockwave Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Macromedia, Adobe</b> | <b>1995-2019</b><br>
    <?= t('Platforms_Adobe_Shockwave_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/alambik.png">
    <span class="title-small">Alambik Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Alambik Limited</b> | <b>2001-2004</b><br>
    <?= t('Platforms_Alambik_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/ambulant.png">
    <span class="title-small">Ambulant</span>
    <hr>
    <b><?= t('Platforms_By') ?> Centrum Wiskunde & Informatica</b> | <b>2003-2016</b><br>
    <?= t('Platforms_Ambulant_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/animaflex.png">
    <span class="title-small">AnimaFlex</span>
    <hr>
    <b><?= t('Platforms_By') ?> RubberFlex Software</b> | <b>1997</b><br>
    <?= t('Platforms_AnimaFlex_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/asapwebshow.png"><img src="images/icons/harvardwebshow.png">
    <span class="title-small">ASAP Webshow / Harvard Graphics WebShow</span>
    <hr>
    <b><?= t('Platforms_By') ?> Software Publishing Corporation / Serif</b> | <b>1996-1998 & 1998-2000</b><br>
    <?= t('Platforms_ASAP_Webshow_Harvard_Graphics_WebShow_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/authorware.png">
    <span class="title-small">Authorware Web Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Macromedia, Adobe</b> | <b>1996-2007</b><br>
    <?= t('Platforms_Authorware_Web_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/mapguide.png">
    <span class="title-small">Autodesk MapGuide</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Autodesk_MapGuide_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/axel.png">
    <span class="title-small">AXEL Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> MindAvenue</b> | <b>2002-2006</b><br>
    <?= t('Platforms_AXEL_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/bitplayer.png">
    <span class="title-small">BitPlayer</span>
    <hr>
    <b><?= t('Platforms_By') ?> BitMagic</b> | <b>1999-2001</b><br>
    <?= t('Platforms_BitPlayer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/blender.png">
    <span class="title-small">Blender 3D Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> Not a Number Technologies, Blender Foundation</b> | <b>2001-2002</b><br>
    <?= t('Platforms_Blender_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/burster.png">
    <span class="title-small">Burster</span>
    <hr>
    <b><?= t('Platforms_By') ?> iTechnologie Ldt.</b> | <b>2010-2016</b><br>
    <?= t('Platforms_Burster_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/calendarquick.png">
    <span class="title-small">Calendar Quick Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Logic Pulse</b> | <b>1996-1999</b><br>
    <?= t('Platforms_Calendar_Quick_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/cult3d.png">
    <span class="title-small">Cult3D</span>
    <hr>
    <b><?= t('Platforms_By') ?> Cycore Computers, Cycore Systems AB</b> | <b>1999-2013</b><br>
    <?= t('Platforms_Cult3D_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/dfusion.png">
    <span class="title-small">D'Fusion @Home Web Plug-In</span>
    <hr>
    <b><?= t('Platforms_By') ?> Total Immersion</b> | <b>2009-2015</b><br>
    <?= t('Platforms_DFusion_Home_Web_PlugIn_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/webanimator.png">
    <span class="title-small">DeltaPoint WebAnimator</span>
    <hr>
    <b><?= t('Platforms_By') ?> DeltaPoint Inc.</b> | <b>??-??</b><br>
    <?= t('Platforms_DeltaPoint_WebAnimator_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/dpgraph.png">
    <span class="title-small">DPGraph</span>
    <hr>
    <b><?= t('Platforms_By') ?> David Parker, DPGraph</b> | <b>1999-2019</b><br>
    <?= t('Platforms_DPGraph_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/eanimator.png">
    <span class="title-small">E-アニメータ / SharpMotionART</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sharp Corporation</b> | <b>2001-2004</b><br>
    <?= t('Platforms_E_Animator_SharpMotionART_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/envoy.png">
    <span class="title-small">Envoy</span>
    <hr>
    <b><?= t('Platforms_By') ?> Tumbleweed Software Corp., Novell</b> | <b>1995-1999</b><br>
    <?= t('Platforms_Envoy_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/eva.png">
    <span class="title-small">EVA</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sharp Corporation</b> | <b>1997-2016</b><br>
    <?= t('Platforms_EVA_Description', '<b>', '<b>', '<b>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/flatlandrover.png">
    <span class="title-small">Flatland Rover</span>
    <hr>
    <b><?= t('Platforms_By') ?> Flatland Online Inc.</b> | <b>1997-2005</b><br>
    <?= t('Platforms_Flatland_Rover_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/formulaone.png">
    <span class="title-small">Formula One</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Formula_One_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/fractalviewer.png">
    <span class="title-small">Fractal Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Fractal_Viewer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/freehand.png">
    <span class="title-small">FreeHand</span>
    <hr>
    <b><?= t('Platforms_By') ?> Macromedia</b> | <b>1996-1998</b><br>
    <?= t('Platforms_FreeHand_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/gobit.png">
    <span class="title-small">GoBit Games Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> GoBit Games</b> | <b>2008-2009</b><br>
    <?= t('Platforms_GoBit_Games_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/hotsauce.png">
    <span class="title-small">HotSauce</span>
    <hr>
    <b><?= t('Platforms_By') ?> Apple Inc.</b> | <b>1996-1997</b><br>
    <?= t('Platforms_HotSauce_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/html.png">
    <span class="title-small">HTML / HTML5</span>
    <hr>
    <b><?= t('Platforms_By') ?> World Wide Web Consortium, WHATWG</b> | <b>1993/1995/1997/2008-Present</b><br>
    <?= t('Platforms_HTML_HTML5_Description', '<b>', '<b>', '<b>', '<b>', '<i>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/hyperg.png">
    <span class="title-small">Hyper-G</span>
    <hr>
    <b><?= t('Platforms_By') ?> Institut für Informationssysteme und Computer Medien (IICM)</b> | <b>1995-1996</b><br>
    <?= t('Platforms_HyperG_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/hypercosm.png">
    <span class="title-small">Hypercosm Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Hypercosm, ORBITEC</b> | <b>1999-2016</b><br>
    <?= t('Platforms_Hypercosm_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/illuminatus.png">
    <span class="title-small">Illuminatus</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Illuminatus_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/ipix.png">
    <span class="title-small">iPix Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_iPix_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/java.png">
    <span class="title-small">Java Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sun Microsystems, Oracle</b> | <b>1995-2018</b><br>
    <?= t('Platforms_Java_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/jcampdx.png">
    <span class="title-small">JCAMP-DX</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_JCAMPDX_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/lightningstrike.png">
    <span class="title-small">Lightning Strike</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Lightning_Strike_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/livepictureviewer.png">
    <span class="title-small">Live Picture Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Live_Picture_Viewer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/livemath.png">
    <span class="title-small">LiveMath Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Prescience Corporation, Waterloo Maple, MathMonkeys</b> | <b>1994-2014</b><br>
    <?= t('Platforms_LiveMath_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/mhsv.png">
    <span class="title-small">MHSV</span>
    <hr>
    <b><?= t('Platforms_By') ?> ParaGraph International</b> | <b>1996</b><br>
    <?= t('Platforms_MHSV_Description', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>', '<b>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/silverlight.png">
    <span class="title-small">Microsoft Silverlight</span>
    <hr>
    <b><?= t('Platforms_By') ?> Microsoft</b> | <b>2007-2021</b><br>
    <?= t('Platforms_Microsoft_Silverlight_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/noteworthycomposer.png">
    <span class="title-small">NoteWorthy Composer Browser Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_NoteWorthy_Composer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/o2cplayer.png">
    <span class="title-small">o2c-Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> mb Software AG, Eleco Software GmbH</b> | <b>1999-Present</b><br>
    <?= t('Platforms_O2C_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/octree.png">
    <span class="title-small">Octree View</span>
    <hr>
    <b><?= t('Platforms_By') ?> Octree Corporation</b> | <b>1998-2007</b><br>
    <?= t('Platforms_Octree_View_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/pixound.png">
    <span class="title-small">Pixound</span>
    <hr>
    <b><?= t('Platforms_By') ?> Hologramophone Research, Frankfurt Balkind Partners, Techné Media</b> | <b>1996-2005</b><br>
    <?= t('Platforms_Pixound_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/deepv.png"><img src="images/icons/play3d.png">
    <span class="title-small">Play3D / DeepV</span>
    <hr>
    <b><?= t('Platforms_By') ?> Mark Carolan, Heads Off</b> | <b>1996-1997 & 1997-2001</b><br>
    <?= t('Platforms_Play3D_DeepV_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/pointplus.png">
    <span class="title-small">PointPlus</span>
    <hr>
    <b><?= t('Platforms_By') ?> Net-Scene</b> | <b>1996-1997</b><br>
    <?= t('Platforms_PointPlus_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/popcap.png">
    <span class="title-small">PopCap Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> PopCap Games</b> | <b>2004-2007</b><br>
    <?= t('Platforms_PopCap_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/protoplay.png">
    <span class="title-small">ProtoPlay</span>
    <hr>
    <b><?= t('Platforms_By') ?> Altia Inc.</b> | <b>1996-2009</b><br>
    <?= t('Platforms_ProtoPlay_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/pulse.png">
    <span class="title-small">Pulse Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Pulse Entertainment</b> | <b>1999-2003</b><br>
    <?= t('Platforms_Pulse_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/rebol.png">
    <span class="title-small">REBOL Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> REBOL Technologies</b> | <b>2004-2006</b><br>
    <?= t('Platforms_REBOL_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/shiva3d.png">
    <span class="title-small">ShiVa Web Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> ShiVa Technologies</b> | <b>2004-2019</b><br>
    <?= t('Platforms_ShiVa_Web_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/showit.png">
    <span class="title-small">Show It!</span>
    <hr>
    <b><?= t('Platforms_By') ?> Corel</b> | <b>1997-2001</b><br>
    <?= t('Platforms_Show_It_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/smoothmovepanorama.png">
    <span class="title-small">SmoothMove Panorama</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_SmoothMove_Panorama_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/squeak.png">
    <span class="title-small">Squeak / Etoys</span>
    <hr>
    <b><?= t('Platforms_By') ?> Viewpoints Research Institute Inc.</b> | <b>2001-2012</b><br>
    <?= t('Platforms_Squeak_Etoys_Description') ?>
	<br style="margin-bottom:20px">

    <img src="images/icons/viscape.png">
    <span class="title-small">Superscape Viscape</span>
    <hr>
    <b><?= t('Platforms_By') ?> Superscape</b> | <b>1996-2000</b><br>
    <?= t('Platforms_Superscape_Viscape_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/surroundvideo.png">
    <span class="title-small">Surround Video</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Surround_Video_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/svfviewer.png">
    <span class="title-small">SVF Viewer / Simple Vector Format Viewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_SVF_Viewer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/tcl.png">
    <span class="title-small">Tcl Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Sun Microsystems, Scriptics, Tcl Core Team</b> | <b>1996-2006</b><br>
    <?= t('Platforms_Tcl_Plugin_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/thingviewer.png">
    <span class="title-small">ThingViewer</span>
    <hr>
    <b><?= t('Platforms_By') ?> Parable Corporation, ThingWorld</b> | <b>1997-2002</b><br>
    <?= t('Platforms_ThingViewer_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/unity.png">
    <span class="title-small">Unity Web Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> Unity Technologies</b> | <b>2005-2016</b><br>
    <?= t('Platforms_Unity_Web_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/webmap.png">
    <span class="title-small">Visual WebMap</span>
    <hr>
    <b><?= t('Platforms_By') ?> Project Development</b> | <b>1997</b><br>
    <?= t('Platforms_Visual_WebMap_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/vitalize.png">
    <span class="title-small">Vitalize!</span>
    <hr>
    <b><?= t('Platforms_By') ?> Corel, Clickteam</b> | <b>1997-2012</b><br>
    <?= t('Platforms_Vitalize_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/vrml.png">
    <span class="title-small">VRML</span>
    <hr>
    <b><?= t('Platforms_By') ?> Web3D Consortium</b> | <b>1994-2001</b><br>
    <?= t('Platforms_VRML_Description', '<b>', '<b>', '<b>', '<b>') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/x3d.png">
    <span class="title-small">X3D / Extensible 3D Graphics</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_X3D_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/xara.png">
    <span class="title-small">Xara Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> Xara Ltd</b> | <b>1996-2000</b><br>
    <?= t('Platforms_Xara_Plugin_Description') ?>
</div>

<span class="title"><?= t('Platforms_Coming_Soon') ?></span>
<hr class="title-divider">
<?= t('Platforms_Coming_Soon_Description') ?>
<div class="border">
    <img src="images/icons/commonground.png">
    <span class="title-small" id="commonground">Common Ground MiniViewer Plug-In</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Common_Ground_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/djvu.png">
    <span class="title-small" id="djvu">DjVu Browser Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_DjVu_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/jamagic.png">
    <span class="title-small" id="jamagic">Jamagic</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Jamagic_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/jutvision.png">
    <span class="title-small" id="jutvision">Jutvision Plug-In</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Jutvision_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/mbed.png">
    <span class="title-small" id="mbed">mBed Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_mBed_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/mrsid.png">
    <span class="title-small" id="mrsid">MrSID Browser Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_MrSID_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/panoramix.png">
    <span class="title-small" id="panoramix">PanoramIX Plugin</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_PanoramIX_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/petzplayer.png">
    <span class="title-small" id="petzplayer">Petz Player</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Petz_Player_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/scorch.png">
    <span class="title-small" id="scorch">Sibelius Scorch</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Sibelius_Scorch_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/sizzler.png">
    <span class="title-small" id="scorch">Sizzler</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Sizzler_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/cool360.png">
    <span class="title-small" id="cool360">Ulead COOL 360 Plug-in</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_Ulead_COOL_360_Description') ?>
    <br style="margin-bottom:20px">

    <img src="images/icons/vream.png">
    <span class="title-small" id="vream">VReam / WIRL Interactive VR Browser</span>
    <hr>
    <b><?= t('Platforms_By') ?> ??</b> | <b>??-??</b><br>
    <?= t('Platforms_VReam_WIRL_Description') ?>
</div>
