<span class="title"><?= t('Source_Title') ?></span>
<hr class="title-divider">
<?= t('Source_Desc', '<a href="https://github.com/FlashpointProject">') ?>
<div class="break-large"></div>

<span class="title-small"><?= t('Source_Developed_Projects_Title') ?></span>
<hr>
<?= t('Source_Developed_Projects_Desc') ?>
<ul>
    <li><?= t('Source_Flashpoint_Launcher_Desc', '<a href="https://github.com/FlashpointProject/launcher">') ?>
    <li><?= t('Source_Flashpoint_Proxy_Desc', '<a href="https://github.com/FlashpointProject/FlashpointProxy">') ?>
    <li><?= t('Source_Flashpoint_Secure_Player_Desc', '<a href="https://github.com/FlashpointProject/FlashpointSecureTools/tree/master/FlashpointSecurePlayer">') ?>
    <li><?= t('Source_Flashpoint_Component_Tools_Desc', '<a href="https://github.com/FlashpointProject/FlashpointComponentTools">') ?>
    <li><?= t('Source_Flashpoint_OldCPUSimulator_Desc', '<a href="https://github.com/tomysshadow/OldCPUSimulator">') ?>
</ul>
<div class="break-large"></div>

<span class="title-small"><?= t('Source_Utilized_Projects_Title') ?></span>
<hr>
<?= t('Source_Utilized_Projects_Desc') ?>
<ul>
    <li><?= t('Source_Apache_Desc', '<a href="https://httpd.apache.org/">') ?>
    <li><?= t('Source_Basilisk_Desc', '<a href="https://basilisk-browser.org/">', '<a href="https://github.com/FlashpointProject/fpnavigator">') ?>
    <li><?= t('Source_Chromium_Desc', '<a href="https://www.chromium.org/Home/">') ?>
    <li><?= t('Source_PHP_Desc', '<a href="https://www.php.net/">') ?>
</ul>